### ISSUE TITLE
commonUtil.js 쪽 질문 드립니다.

### ISSUE THREAD

**Issue by ddarkchu** [SKplanet/sweetswipe#2]
getTranslate3dX 함수에서 아래 코드 중 "+sPreCss"의 "+" 가 무슨의미인지 궁금하네요....
 let nPreX = +sPreCss.replace(/translate3d((-_\d+(?:.\d+)_)(px)*\,.+)/g , "$1");

**Comment by crongro** [comment]
For type conversion : -)

http://stackoverflow.com/questions/1133770/how-do-i-convert-a-string-into-an-integer-in-javascript

**Comment by portars** [comment]
thank you so much ~~ : )
